apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.openshift.io: https://github.com/openshift/api/pull/2044
    api.openshift.io/filename-cvo-runlevel: "0000_00"
    api.openshift.io/filename-operator: cluster-version-operator
    api.openshift.io/filename-ordering: "01"
    feature-gate.release.openshift.io/ClusterVersionOperatorConfiguration: "true"
  name: clusterversionoperators.operator.openshift.io
spec:
  group: operator.openshift.io
  names:
    kind: ClusterVersionOperator
    listKind: ClusterVersionOperatorList
    plural: clusterversionoperators
    singular: clusterversionoperator
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: "ClusterVersionOperator holds cluster-wide information about
          the Cluster Version Operator. \n Compatibility level 1: Stable within a
          major release for a minimum of 12 months or 3 minor releases (whichever
          is longer)."
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: spec is the specification of the desired behavior of the
              Cluster Version Operator.
            properties:
              operatorLogLevel:
                default: Normal
                description: "operatorLogLevel is an intent based logging for the
                  operator itself.  It does not give fine grained control, but it
                  is a simple way to manage coarse grained logging choices that operators
                  have to interpret for themselves. \n Valid values are: \"Normal\",
                  \"Debug\", \"Trace\", \"TraceAll\". Defaults to \"Normal\"."
                enum:
                - ""
                - Normal
                - Debug
                - Trace
                - TraceAll
                type: string
            type: object
          status:
            description: status is the most recently observed status of the Cluster
              Version Operator.
            properties:
              observedGeneration:
                description: observedGeneration is the last generation change you've
                  dealt with
                format: int64
                type: integer
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
